plugin: netbox.netbox.nb_inventory
api_endpoint: http://10.100.26.156:8000
token: 4462a5c4afcfde6663479400d5e7206bb7e73cf4
validate_certs: False

group_by:
  - sites
  - tenants
  - racks
  - tags
  - device_roles
  - device_types
  - manufacturers
  - platforms
  - region
  - cluster
  - cluster_type
  - cluster_group
  - is_virtual
  - services
  - status
  - time_zone
  - utc_offset
  - facility

compose:
  ansible_network_os: platform.slug
  ansible_host: primary_ip4.address.split('/')[0]

