- name: Ensure VLAN 100 exists in NetBox
  hosts: localhost
  gather_facts: false
  collections:
    - netbox.netbox
  tasks:
    - name: Create VLAN 100 in site “ITCP”
      netbox.netbox.netbox_vlan:
        netbox_url: http://10.100.26.156:8000
        netbox_token: "{{ lookup('env','NETBOX_API_TOKEN') }}"
        data:
          vid: 100
          name: "Users_VLAN"
          site: "ITCP"
          status: "active"
