- name: Render & push VLAN from NetBox to device
  hosts: switches
  gather_facts: false
  collections:
    - netbox.netbox
    - ansible.netcommon
  tasks:
    - name: Fetch VLAN info from NetBox
      netbox.netbox.netbox_vlan_info:
        netbox_url: http://10.100.26.156:8000
        netbox_token: "{{ lookup('env','NETBOX_API_TOKEN') }}"
        filters:
          vid: 100
      register: vlan_info

    - name: Set vlan fact
      set_fact:
        vlan: "{{ vlan_info.vlans[0] }}"

    - name: Render IOS VLAN template
      template:
        src: templates/ios_vlan.j2
        dest: /tmp/{{ inventory_hostname }}-vlan100.cfg

    - name: Push configuration to device
      ios_config:
        src: /tmp/{{ inventory_hostname }}-vlan100.cfg
      when: vlan_info.vlans | length > 0
